### ISSUE TITLE
Periodic status changes when door not opened/closed

### ISSUE THREAD

**Issue by lukescott** [ratgdo/mqtt-ratgdo#12]
I have two Security 1.0 doors integrated into HomeAssistant. I'm getting periodic status changes where it will say the door opened, but then immediately closed. Here is some logs from HomeAssistant:

<img width="289" alt="Screenshot 2023-11-26 at 10 21 31 AM" src="https://github.com/ratgdo/mqtt-ratgdo/assets/486224/30ba9710-f3aa-4642-9e8a-64be6c1f3471">
<img width="276" alt="Screenshot 2023-11-26 at 10 20 39 AM" src="https://github.com/ratgdo/mqtt-ratgdo/assets/486224/963b15e3-c654-4e89-9473-849956afc0e6">

During this time I have not opened the garage door, and as you can see, the time in-between status changes are very short.

**Comment by PaulWieland** [comment]
A few people have seen this. Not much can be done about the door reporting the wrong status. I could have it ignore short status changes, but then it would add a delay in updating whenever the door state really changes.

**Comment by lukescott** [comment]
@PaulWieland Is there anything we can do to look into this a little deeper? This is a fairly big problem. I can't have this reporting the door is open when it's not. If the door actually opens, then I'm bound to ignore it as a false positive.

The only other thing I can think of it the dummy button has some capacitors in it. I'm going to try and disconnect one and monitor it from there. But if this issue persists, I need a way to debug this and get to the root cause.

**Comment by Snuffy2** [comment]
I know this is already closed, but I'd agree that it would be helpful if something could be done to filter these out.

![SNAG-2670](https://github.com/ratgdo/mqtt-ratgdo/assets/6526076/fdda131a-b6f6-4298-b421-c9fd1cba7778)

**Comment by Snuffy2** [comment]
For now, I've put a Template Cover in HA that is now what Automations and HomeKit are using to reduce false alerts.

```yaml
cover:
  - platform: template
    covers:
      garage_door_bikes:
        device_class: garage
        friendly_name: "Garage Door - Bikes"
        unique_id: garage_door_bikes_safe
        value_template: >-
          {% if is_state('cover.garage_door_bikes_mqtt',states('cover.garage_door_bikes')) %}
          {{ states('cover.garage_door_bikes') }}
          {% elif (is_state('cover.garage_door_bikes','opening') and is_state('cover.garage_door_bikes_mqtt','open') and (as_timestamp(now()) - as_timestamp(states.cover.garage_door_bikes_mqtt.last_changed)) <= 5) %}
          opening
          {% elif (is_state('cover.garage_door_bikes_mqtt','open') and (as_timestamp(now()) - as_timestamp(states.cover.garage_door_bikes_mqtt.last_changed)) > 5) or is_state('cover.garage_door_bikes_mqtt',['opening','closing','closed']) %}
          {{ states('cover.garage_door_bikes_mqtt') }}
          {% else %}
          closed
          {% endif %}
        open_cover:
          - service: cover.open_cover
            target:
              entity_id: cover.garage_door_bikes_mqtt
        close_cover:
          - service: cover.close_cover
            target:
              entity_id: cover.garage_door_bikes_mqtt
        stop_cover:
          - service: cover.stop_cover
            target:
              entity_id: cover.garage_door_bikes_mqtt      
```
